server:
  port: 8081

spring:
  application:
    name: scrapper

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:linktracker_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        reWriteBatchedInserts: true

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.hibernate.jdbc.batch_size: 50
      hibernate:
        generate_statistics: true

  grpc:
    server:
      port: 9091

app:
  db:
    workers:
      link-update:
        batch-size: 12
        flush-timeout: 200
        core-pool-size: 2
        max-pool-size: 4
        queue-capacity: 0
        maximum-number-of-unprocessed-elements: 10000
    access-type: orm

  scheduler:
    enabled: true
    link-update:
      batch-size: 50
      interval-update-ms: 60000

  cache:
    enabled: true
    local:
      ttl: 10m
      max-size: 10000
    redis:
      ttl: 10m

  client:
    api-workers:
      thread-pool-size: 4
      queue-capacity: 10

    stackoverflow:
      host: https://api.stackexchange.com/2.3
      key: ${STACKOVERFLOW_KEY}
      access-token: ${STACKOVERFLOW_ACCESS_TOKEN}

    github:
      host: https://api.github.com
      token: ${GITHUB_TOKEN}

    bot:
      host: ${APP_CLIENT_BOT_HOST:http://localhost:8080}
      grpc-host: ${APP_CLIENT_BOT_GRPC_HOST:localhost:9090}

      api:
        kafka:
          enabled: true
        rest:
          enabled: true
        grpc:
          enabled: false

logging:
  level:
    org.hibernate.sql: DEBUG
