spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:linktracker_db}
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

app:

  db:
    access-type: orm

  scheduler:
    enabled: false
    metrics:
      enabled: false
    link-update:
      enabled: false

  cache:
    enabled: false

  client:
    bot:
      api:
        kafka:
          enabled: false
        rest:
          enabled: true
        grpc:
          enabled: false

management:
  health:
    redis:
      enabled: false
