management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true

spring:
  config:
    activate:
      on-profile: kafka

  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

    producer:
      properties:
        acks: 1
        batch.size: 1024
        linger.ms: 10000
        schema.registry.url: http://localhost:8087

app:
  scheduler:
    outbox:
      enabled: true
      batch-size: 50
      interval-update-ms: 60000
    old-event:
      interval-timeout-min: 10

  db:
    workers:
      outbox-update:
        batch-size: 12
        flush-timeout: 200
        core-pool-size: 2
        max-pool-size: 4
        queue-capacity: 0
        maximum-number-of-unprocessed-elements: 10000

  kafka:
    serialization: avro

    topics:
      link-raw-updates:
        name: link-raw-updates
        partitions: 3
        replicas: 3
      link-updates:
        name: link-updates
        partitions: 3
        replicas: 3
