server:
  port: 8081

spring:
  application:
    name: scrapper

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:linktracker_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        reWriteBatchedInserts: true

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.hibernate.jdbc.batch_size: 50
      hibernate:
        generate_statistics: true

  grpc:
    server:
      port: 9091

app:
  db:
    workers:
      link-update:
        batch-size: 12
        flush-timeout: 200
        core-pool-size: 2
        max-pool-size: 4
        queue-capacity: 0
        maximum-number-of-unprocessed-elements: 10000
    access-type: orm

  scheduler:
    enabled: false
    link-update:
      batch-size: 50
      interval-update-ms: 60000

  cache:
    enabled: true
    local:
      ttl: 10m
      max-size: 10000
    redis:
      ttl: 10m

  client:
    api-workers:
      thread-pool-size: 4
      queue-capacity: 10

    stackoverflow:
      host: https://api.stackexchange.com/2.3
      key: ${STACKOVERFLOW_KEY}
      access-token: ${STACKOVERFLOW_ACCESS_TOKEN}

    github:
      host: https://api.github.com
      token: ${GITHUB_TOKEN}

    bot:
      host: ${APP_CLIENT_BOT_HOST:http://localhost:8080}
      grpc-host: ${APP_CLIENT_BOT_GRPC_HOST:localhost:9090}
      timeout:
        connection: 1s
        read: 1s

      api:
        kafka:
          enabled: false
        rest:
          enabled: true
        grpc:
          enabled: false

resilience4j:

  ratelimiter:
    rate-limiter-aspect-order: 1
    configs:
      default:
        register-health-indicator: true
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 100
    instances:
      sendUpdateLimiter:
        base-config: default
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 0s

      githubRepositoryLimiter:
        limit-for-period: 30
        limit-refresh-period: 1m
        timeout-duration: 0s

      githubIssuesLimiter:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 0s

      stackQuestionLimiter:
        limit-for-period: 25
        limit-refresh-period: 1m
        timeout-duration: 0s

      stackAnswerLimiter:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 0s

      stackCommentLimiter:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 0s

  circuitbreaker:
    circuit-breaker-aspect-order: 2
    instances:
      botApi:
        failure-rate-threshold: 70
        sliding-window-size: 20
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.botexception.responsexception.BotServerException

      githubApi:
        failure-rate-threshold: 50
        sliding-window-size: 20
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

      stackOverflowApi:
        failure-rate-threshold: 50
        sliding-window-size: 20
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

  retry:
    retry-aspect-order: 3
    instances:
      githubRepositoryRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

      githubIssuesRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

      stackQuestionRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

      stackAnswerRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

      stackCommentRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - backend.academy.linktracker.scrapper.exception.externalexception.ExternalApiServerException

logging:
  level:
    org.hibernate.sql: DEBUG
    org.springframework.data.redis: DEBUG
