server:
  port: 8080

spring:
  application:
    name: bot

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: false

  grpc:
    server:
      port: 9090

  devtools:
    restart:
      enabled: false

app:

  proxy:
    host: ${PROXY_HOST}
    port: ${PROXY_PORT}
    pass: ${PROXY_PASS}
    user-name: ${PROXY_USER_NAME}
  telegram:
    enabled: true
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

  db:
    access-type: orm

  logger:
    path: ./logs

    console:
      enabled: true

    file:
      enabled: false

  client:
    scrapper:
      host: ${APP_CLIENT_SCRAPPER_HOST:http://localhost:8081}
      grpc-host: ${APP_CLIENT_SCRAPPER_GRPC_HOST:localhost:9091}
      timeout:
        connection: 1s
        read: 1s

      api:
        kafka:
          enabled: true
        rest:
          enabled: true
        grpc:
          enabled: false

#logging:
#  level:
#    org.apache.kafka: TRACE
#    org.springframework.kafka: DEBUG
#    org.springframework.kafka.support.serializer: TRACE

management:
  server:
    port: 8011

  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
      path-mapping:
        prometheus: metrics

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    tags:
      application: bot
