server:
  port: 8080

spring:
  application:
    name: bot

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/bot_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  grpc:
    server:
      port: 9090

  devtools:
    restart:
      enabled: false

app:
  telegram:
    enabled: true
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

  db:
    access-type: orm

  logger:
    path: ./logs

    console:
      enabled: true

    file:
      enabled: false

  client:
    scrapper:
      host: ${APP_CLIENT_SCRAPPER_HOST:http://localhost:8081}
      grpc-host: ${APP_CLIENT_SCRAPPER_GRPC_HOST:localhost:9091}
      timeout:
        connection: 1s
        read: 1s

      api:
        kafka:
          enabled: true
        rest:
          enabled: true
        grpc:
          enabled: false

resilience4j:
  retry:
    retry-aspect-order: 1
    instances:
      getLinksRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      addLinkRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      untrackLinkRetry:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      registerChatRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      deleteChatRetry:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException

  circuitbreaker:
    circuit-breaker-aspect-order: 2
    instances:
      scrapperApi:
        failure-rate-threshold: 70
        sliding-window-size: 20
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        record-exceptions:
          - backend.academy.linktracker.bot.exception.scrapperexception.responsexception.ScrapperServerException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException

  ratelimiter:
    rate-limiter-aspect-order: 3
    configs:
      default:
        register-health-indicator: true
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 100
    instances:
      registerChatLimiter:
        base-config: default
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 1s

      deleteChatLimiter:
        base-config: default
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0

      getLinksLimiter:
        base-config: default
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 200ms

      addLinkLimiter:
        base-config: default
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 500ms

      untrackLinkLimiter:
        base-config: default
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0

logging:
  level:
    org.apache.kafka: TRACE
    org.springframework.kafka: DEBUG
    org.springframework.kafka.support.serializer: TRACE
