server:
  port: 8080

spring:
  application:
    name: bot
  grpc:
    server:
      port: 9090

app:
  telegram:
    enabled: true
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  logger:
    path: ./logs
    console:
      enabled: true
    file:
      enabled: false
  client:
    scrapper:
      host: http://localhost:8081
      grpc-host: localhost:9091
      api: both




