spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

    consumer:
      properties:
        enable.auto.commit: false
        auto-offset-reset: earliest
        isolation.level: read_committed
        fetch.min.bytes: 1024
        fetch.max.bytes: 1048576
        fetch.max.wait.ms: 1000
        max.poll.interval.ms: 300000
        max.poll.records: 50
        schema.registry.url: http://localhost:8087
        spring.json.trusted.packages: "backend.academy.linktracker.bot"

    producer:
      acks: all

      properties:
        schema.registry.url: http://localhost:8087
        auto.register.schemas: true

app:
  kafka:
    serialization: json

    topics:
      link-update: link-updates
      concurrency: 3
