version: '3.9'

networks:
  backend:
    driver: bridge

services:
  kafka-0:
    image: apache/kafka:latest
    container_name: kafka-0
    hostname: kafka-0
    networks:
      - backend
    ports:
      - "29092:29092"
    environment:
      # Для генерации использовалось docker run --rm confluentinc/cp-kafka:8.1.0 kafka-storage random-uuid
      CLUSTER_ID: sCDScDp-QciBWODUUlC3Hw
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://kafka-0:9092,CONTROLLER://kafka-0:9093,DOCKER://0.0.0.0:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-0:9092,DOCKER://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_REPLICATION_FACTOR: 3

  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    networks:
      - backend
    ports:
      - "29093:29093"
    environment:
      # Для генерации использовалось docker run --rm confluentinc/cp-kafka:8.1.0 kafka-storage random-uuid
      CLUSTER_ID: sCDScDp-QciBWODUUlC3Hw
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://kafka-1:9092,CONTROLLER://kafka-1:9093,DOCKER://0.0.0.0:29093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-1:9092,DOCKER://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_REPLICATION_FACTOR: 3

  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    networks:
      - backend
    ports:
      - "29094:29094"
    environment:
      # Для генерации использовалось docker run --rm confluentinc/cp-kafka:8.1.0 kafka-storage random-uuid
      CLUSTER_ID: sCDScDp-QciBWODUUlC3Hw
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://kafka-2:9092,CONTROLLER://kafka-2:9093,DOCKER://0.0.0.0:29094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-2:9092,DOCKER://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_REPLICATION_FACTOR: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - schema-registry
    networks:
      - backend
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    volumes:
      - ./kui/mulit-broker-config.yml:/etc/kafkaui/config.yaml
      - ./kui/mulit-broker-config.yml:/etc/kafkaui/dynamic_config.yaml

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.8
    container_name: schema-registry
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8081/subjects || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend
    ports:
      - "8087:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092
      #SCHEMA_REGISTRY_DEBUG: 'true'

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d
#    ports:
#      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  liquibase:
    container_name: liquibase-migrations
    image: liquibase/liquibase:4.29
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --searchPath=/changesets
      - --changelog-file=changelog-root.yaml
      - --url=jdbc:postgresql://postgres:5432/${DB_NAME}
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ../migrations/migrations-k6-test:/changesets
#      - ../migrations/migrations-scrapper:/changesets
    networks:
      - backend

  liquibase-bot:
    container_name: liquibase-bot
    image: liquibase/liquibase:4.29

    depends_on:
      postgres:
        condition: service_healthy

    command:
      - --searchPath=/changesets
      - --changelog-file=changelog-root.yaml
      - --url=jdbc:postgresql://postgres:5432/bot_db
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update

    volumes:
      - ../migrations/migrations-bot:/changesets

    networks:
      - backend

  ai-agent:
    container_name: ai-agent
    build:
      context: ../ai-agent
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    ports:
      - "8085:8085"
    networks:
      - backend
    depends_on:
      schema-registry:
        condition: service_healthy

  bot:
    build:
      context: ../bot
    env_file:
      - ../.env
    container_name: bot
    depends_on:
      liquibase-bot:
        condition: service_completed_successfully
      scrapper:
        condition: service_healthy
    environment:
      APP_CLIENT_SCRAPPER_HOST: http://scrapper:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bot_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - backend

  scrapper:
    build:
      context: ../scrapper
    env_file:
      - ../.env
    container_name: scrapper
    depends_on:
      schema-registry:
        condition: service_healthy
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      valkey-0:
        condition: service_started
      valkey-1:
        condition: service_started
      valkey-2:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8081/actuator/health/readiness || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    environment:
      SPRING_PROFILES_ACTIVE: kafka,valkey-cluster-config
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_CLIENT_BOT_HOST: http://bot:8080
      APP_CLIENT_BOT_GRPC_HOST: bot:9090
      SPRING_DATA_REDIS_CLUSTER_NODES: valkey-0:6379,valkey-1:6379,valkey-2:6379
    ports:
      - "8081:8081"
      - "9091:9091"
    networks:
      - backend

  valkey-0:
    image: bitnamilegacy/valkey-cluster:8.1.3
    container_name: valkey-0
    ports:
      - "6379:6379"
    networks:
      - backend
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      VALKEY_CLUSTER_REPLICAS: 1
      VALKEY_NODES: "valkey-0 valkey-1 valkey-2"
      VALKEY_CLUSTER_CREATOR: "yes"
    volumes:
      - valkey-cluster_data-0:/bitnami/valkey/data
    depends_on:
      - valkey-1
      - valkey-2

  valkey-1:
    image: bitnamilegacy/valkey-cluster:8.1.3
    container_name: valkey-1
    ports:
      - "6380:6379"
    networks:
      - backend
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      VALKEY_NODES: "valkey-0 valkey-1 valkey-2"
    volumes:
      - valkey-cluster_data-1:/bitnami/valkey/data

  valkey-2:
    image: bitnamilegacy/valkey-cluster:8.1.3
    container_name: valkey-2
    ports:
      - "6381:6379"
    networks:
      - backend
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      VALKEY_NODES: "valkey-0 valkey-1 valkey-2"
    volumes:
      - valkey-cluster_data-2:/bitnami/valkey/data

volumes:
  valkey-cluster_data-0:
    driver: local
  valkey-cluster_data-1:
    driver: local
  valkey-cluster_data-2:
    driver: local
